' Launches start.ps1 with hidden PowerShell window. Edit SkinScript/OpenCodePath
' if your layout differs. Generated by setup-autostart.ps1.
Set shell = CreateObject("WScript.Shell")
shell.Run chr(34) & "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" & chr(34) & _
  " -WindowStyle Hidden -ExecutionPolicy Bypass -File """ & "D:\oc-skin\windows\scripts\start.ps1" & """", _
  0, False